version: '3'

services:
  app:
    image: hitalos/laravel:latest
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
    environment:
      - "DB_HOST=database"
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"