version: '3'

services:
  app:
    build: .
    ports:
      - 80:80
    working_dir:
      - /duoc/duoc_quiz
    environment:
      - "DB_HOST=database"
    depends_on:
      - database

  database:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"