version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./public:/var/www/public
    ports:
      - 80:80
  app:
    build: .
    working_dir:
      - /duoc/duoc_quiz
    environment:
      - "DB_HOST=database"
    depends_on:
      - database

  database:
    image: mysql:5.7
    expose:
      - 3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"